version: '3.8'
networks:
  mynet:
    driver: bridge
services:
  database-service:
    container_name: microservice-database
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3307:3306
    networks:
      - mynet
    volumes:
      - ./database:/docker-entrypoint-initdb.d
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    environment:
      PMA_HOST: microservice-database
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: on-failure
    ports:
      - 3333:80
    networks:
      - mynet
  order-service:
    depends_on:
      - database-service
      - rabbitmq3
    build: ./order-service
    volumes:
      - ./order-service:/order-service
      - ~/m2:/root/m2
    working_dir: /order-service
    ports:
      - 8081:8080
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
    command: mvn clean spring-boot:run
    networks:
      - mynet
  payment-service:
    depends_on:
      - database-service
      - rabbitmq3
    build: ./payment-service
    volumes:
      - ./payment-service:/payment-service
      - ~/m2:/root/m2
    working_dir: /payment-service
    ports:
      - 8082:8080
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
    command: mvn clean spring-boot:run
    networks:
      - mynet
  inventory-service:
    depends_on:
      - database-service
      - rabbitmq3
    build: ./inventory-service
    volumes:
      - ./inventory-service:/inventory-service
      - ~/m2:/root/m2
    working_dir: /inventory-service
    ports:
      - 8083:8080
    environment:
        - SPRING_RABBITMQ_HOST=rabbitmq
    command: mvn clean spring-boot:run
    networks:
      - mynet
  authentication-service:
    container_name: authentication-service
    build: ./authentication-service
    volumes:
        - ./authentication-service:/usr/src/authentication-service
        - ~/m2:/root/.m2
    working_dir: /usr/src/authentication-service
    ports:
        - 9898:8080
    command: mvn clean spring-boot:run
    networks:
      - mynet
  rabbitmq3:
    container_name: rabbitmq
    image: rabbitmq:3.8-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      # AMQP protocol port
      - 5672:5672
      # HTTP management UI
      - 15672:15672
    networks:
      - mynet
  keycloak:
    image: jboss/keycloak:4.8.3.Final
    restart: on-failure
    command:
      - "-b"
      - "0.0.0.0"
      - "-Dkeycloak.migration.action=import"
      - "-Dkeycloak.migration.provider=dir"
      - "-Dkeycloak.migration.dir=/config/"
      - "-Dkeycloak.migration.strategy=IGNORE_EXISTING"
    volumes:
      - ./config:/config/
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=MYSQL
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_ADDR=database-service
      - DB_PORT=3306
      - DB_DATABASE=keycloak_database
    ports:
      - "8989:8080"
    networks:
      - mynet
    depends_on:
      - database-service